CONSTANT cs_copy_from      STRING = "[FROM]"
CONSTANT cs_copy_to        STRING = "[ TO ]"

CONSTANT cs_new_line STRING = "\n"

CONSTANT cs_default_lang  STRING = "zh_TW"
CONSTANT cs_erp_path      STRING = "ERP"

#Document Type Define

CONSTANT cs_doc_type_all     STRING = "ALL"
CONSTANT cs_doc_type_4rp     STRING = "4RP"
CONSTANT cs_doc_type_code    STRING = "CODE"
CONSTANT cs_doc_type_cspec   STRING = "CSPEC"
CONSTANT cs_doc_type_gcode   STRING = "GCODE"
CONSTANT cs_doc_type_rspec   STRING = "RSPEC"
CONSTANT cs_doc_type_spec    STRING = "SPEC"
CONSTANT cs_doc_type_specgen STRING = "SPECGEN"

CONSTANT cs_zip_name_tzc STRING = "tzc"
CONSTANT cs_zip_name_tzd STRING = "tzd"
CONSTANT cs_zip_name_tzg STRING = "tzg"
CONSTANT cs_zip_name_tzr STRING = "tzr"
CONSTANT cs_zip_name_tzs STRING = "tzs"
CONSTANT cs_zip_name_tzt STRING = "tzt"
CONSTANT cs_zip_name_tzp STRING = "tzp"

CONSTANT cs_zip_name_tzgt STRING = "tztt"

CONSTANT cs_upload_string STRING = "_up"

CONSTANT cs_client_temp_dir STRING = "c:\\t100temp"
CONSTANT cs_dos_separator   STRING = "\\"
CONSTANT cs_unix_separator  STRING = "/"

CONSTANT cs_open_dialog_caption STRING = "Open 4RP Directory"

CONSTANT cs_message_designer       STRING = "   Designer   "
CONSTANT cs_message_generator      STRING = "  Generator   "    
CONSTANT cs_message_user_control   STRING = " User Control "
CONSTANT cs_message_separator      STRING = "================================================================================"
CONSTANT cs_message_half_separator STRING = "================================"
