CONSTANT cs_null_value STRING = "!@#"      
CONSTANT cs_master_db  STRING = "ds"

#Arguments
CONSTANT cs_args_source_working_type STRING = "-SWT"
CONSTANT cs_args_source_design_name  STRING = "-SDN"
CONSTANT cs_args_source_schema_name  STRING = "-SSN"
CONSTANT cs_args_source_table_name   STRING = "-STN" 
CONSTANT cs_args_source_file_name    STRING = "-SFN"  

CONSTANT cs_args_dest_working_type STRING = "-DWT"
CONSTANT cs_args_dest_design_name  STRING = "-DDN"
CONSTANT cs_args_dest_schema_name  STRING = "-DSN"
CONSTANT cs_args_dest_table_name   STRING = "-DTN" 
CONSTANT cs_args_dest_file_name    STRING = "-DFN"  

CONSTANT cs_args_export_file_type STRING = "-EFT"

#Options
CONSTANT cs_args_send_to_client   STRING = "-STC"
CONSTANT cs_args_GUI_mode         STRING = "-GUI"
CONSTANT cs_args_shipping_diff    STRING = "-SHIP"

CONSTANT cs_default_lang STRING = "zh_TW"

CONSTANT cs_response_cancel STRING = "cancel" 

CONSTANT cs_data_source  STRING = "SOURCE"
CONSTANT cs_data_dest    STRING = "DEST"

CONSTANT cs_schema_owner_all STRING = "ALL"
CONSTANT cs_schema_table_all STRING = "ALL"

CONSTANT cs_working_type_db     STRING = "DB"
CONSTANT cs_working_type_design STRING = "DESIGN"
CONSTANT cs_working_type_file   STRING = "FILE"

CONSTANT cs_design_owner_name STRING = "DESIGN"

CONSTANT cs_log_reserve_days STRING = "7"  

CONSTANT cs_export_txt STRING = "txt"
CONSTANT cs_export_csv STRING = "csv"
CONSTANT cs_export_sql STRING = "sql"

CONSTANT cs_system_module_list = "'ADZ','AZZ','AWS','ARP'"
