#Primary Key Constant
CONSTANT cs_null_value        STRING = "!@#"      

CONSTANT cs_top_module_name   STRING = "TOP"
CONSTANT cs_database          STRING = "Database"

CONSTANT cs_reversion         STRING = "rev"

CONSTANT cs_master_db         STRING = "ds"
CONSTANT cs_master_user       STRING = "ds"

CONSTANT cs_local_db          STRING = "local"

CONSTANT cs_question_yes      STRING = "yes"    
CONSTANT cs_question_no       STRING = "no" 

CONSTANT cs_result_success    STRING = "Success"    
CONSTANT cs_result_fail       STRING = "Fail" 
CONSTANT cs_result_cancel     STRING = "Cancel"    

CONSTANT cs_init_version_code STRING = '0'
CONSTANT cs_init_alm_ver_code STRING = '0'

CONSTANT cs_no_define          STRING = 'NoDefine'
 
CONSTANT cs_template_words    STRING = "template"

CONSTANT cs_sql_go_sign       STRING = "/"

CONSTANT cs_default_lang      STRING = "zh_TW"

CONSTANT cs_order_by_asc      STRING = "ASC"
CONSTANT cs_order_by_desc     STRING = "DESC"

CONSTANT cs_message_hint      STRING = "Hint"
CONSTANT cs_message_warning   STRING = "Warning"
CONSTANT cs_message_error     STRING = "Error"

CONSTANT cs_recompile_object  STRING = "recompobj"

#Parameter Level
CONSTANT cs_param_level_system  STRING = "System"

#System Level
CONSTANT cs_param_master_db    STRING = "MasterDB"
CONSTANT cs_param_master_user  STRING = "MasterUser"

CONSTANT cs_working_unknow_object STRING = "UNKNOW"

#Argument Types
CONSTANT cs_args_table_name  STRING = "-T"

