CONSTANT cs_zip_name_tzc STRING = "tzc"
CONSTANT cs_zip_name_tzd STRING = "tzd"
CONSTANT cs_zip_name_tzg STRING = "tzg"
CONSTANT cs_zip_name_tzr STRING = "tzr"
CONSTANT cs_zip_name_tzs STRING = "tzs"
CONSTANT cs_zip_name_tzt STRING = "tzt"
CONSTANT cs_zip_name_tzp STRING = "tzp"

CONSTANT cs_zip_name_tzx STRING = "tzx" #170208-00008

CONSTANT cs_zip_name_tzgt STRING = "tztt"

CONSTANT cs_zip_name_tmc STRING = "tmc"
CONSTANT cs_zip_name_tmd STRING = "tmd"
CONSTANT cs_zip_name_tmg STRING = "tmg"
CONSTANT cs_zip_name_tmr STRING = "tmr"
CONSTANT cs_zip_name_tms STRING = "tms"
CONSTANT cs_zip_name_tmt STRING = "tmt"
CONSTANT cs_zip_name_tmp STRING = "tmp"

CONSTANT cs_zip_name_tmgt STRING = "tmtt"

CONSTANT cs_download_type_all     = "ALL"
CONSTANT cs_download_type_4rp     = "4RP"
CONSTANT cs_download_type_code    = "CODE"
CONSTANT cs_download_type_cspec   = "CSPEC"
CONSTANT cs_download_type_gcode   = "GCODE"
CONSTANT cs_download_type_rspec   = "RSPEC"
CONSTANT cs_download_type_spec    = "SPEC"
CONSTANT cs_download_type_specgen = "SPECGEN"

CONSTANT cs_run_type_normal = "NORMAL"
CONSTANT cs_run_type_alm    = "ALM"

CONSTANT cs_runtime_mode_debug     = "DEBUG"
CONSTANT cs_runtime_mode_program   = "PROGRAM"
CONSTANT cs_runtime_mode_component = "COMPONENT"

CONSTANT cs_download_string = "_down"

CONSTANT cs_runtime_dir     STRING = "DIR"
CONSTANT cs_client_temp_dir STRING = "c:\\t100temp"
CONSTANT cs_dos_separator   STRING = "\\"

CONSTANT cs_default_lang       STRING  = "zh_TW"
CONSTANT cs_erp_path           STRING  = "ERP"
CONSTANT ci_default_enterprise INTEGER = 99

CONSTANT cs_message_designer       STRING = "   Designer   "
CONSTANT cs_message_generator      STRING = "  Generator   "    
CONSTANT cs_message_user_control   STRING = " User Control "
CONSTANT cs_message_separator      STRING = "================================================================================"
CONSTANT cs_message_half_separator STRING = "================================"
