#Primary Key Constant

CONSTANT cs_new_line          STRING = "\n"     

CONSTANT cs_slave_user        STRING = "dsdemo"

CONSTANT cs_dept              STRING = "None"

CONSTANT cs_synonym_shorthand STRING = "S"
CONSTANT cs_table_shorthand   STRING = "T"

CONSTANT cs_modify_template   STRING = "modtpl"
CONSTANT cs_modify_trigger    STRING = "modtrg"
CONSTANT cs_drop_trigger      STRING = "drptrg"

CONSTANT cs_side_left  STRING = "LEFT"
CONSTANT cs_side_right STRING = "RIGHT"

CONSTANT cs_trigger_type_row       STRING = "row"
CONSTANT cs_trigger_type_statement STRING = "statement"

CONSTANT cs_null_username_default STRING = "Tester"

#Parameter Level define
CONSTANT cs_param_level_trigger STRING = "Trigger"

#Trigger Level
CONSTANT cs_param_event STRING = "Event"

CONSTANT cs_response_cancel STRING = "cancel" 

CONSTANT cs_lang_zh_cn  STRING = "zh_CN"
CONSTANT cs_lang_zh_tw  STRING = "zh_TW"

CONSTANT cs_trigger_keyword_begin STRING = "BEGIN"

CONSTANT cs_exclude_keyword_delete STRING = "DELETE"
CONSTANT cs_exclude_keyword_update STRING = "UPDATE"

CONSTANT cs_mdm_module_name STRING = "MDM"

CONSTANT cs_type_std_to_cust STRING = "STD_TO_CUST"   #標準轉客制  --DGW07558_add_at20160105
CONSTANT cs_type_cust_to_std STRING = "CUST_TO_STD"   #客制還原標準  --DGW07558_add_at20160105
