CONSTANT cs_default_lang    STRING = "zh_TW"
CONSTANT cs_exp_aps_dzlm003 STRING = "[export_for_aps]"

CONSTANT cs_args_table_name STRING = "-T"

CONSTANT ci_construct_no = 9999999999
CONSTANT ci_version_no   = 9999999999

CONSTANT cs_reauest_no  VARCHAR(20) = "999999-99999"
CONSTANT ci_reauest_seq INTEGER     = 99999

CONSTANT cs_aps_exp_xml_ref  VARCHAR(25) = "aps_export_tables.xml"
CONSTANT cs_aps_exp_patch_no VARCHAR(20) = "APS9999999"

CONSTANT cs_exp_table_pack_path STRING = "[Table_Pack_Path]"
CONSTANT cs_exp_table_pack_name STRING = "[Table_Pack_Name]"

CONSTANT cs_null_value STRING = "!@#"      
