CONSTANT cs_progress_tag    STRING = "[PROGRESS]"
CONSTANT cs_message_tag     STRING = "[MESSAGE]"
CONSTANT cs_version_tag     STRING = "[VERSION]"
CONSTANT cs_error_tag       STRING = "[ERROR]"
CONSTANT cs_break_error_tag STRING = "[BREAK_ERROR]"
CONSTANT cs_warning_tag     STRING = "[WARNING]"
CONSTANT cs_information_tag STRING = "[Information]"
CONSTANT cs_command_tag     STRING = "[COMMAND]"
CONSTANT cs_debug_tag       STRING = "[DEBUG]"
CONSTANT cs_parameter_tag   STRING = "[PARAMETER]"
CONSTANT cs_ignore_tag      STRING = "[IGNORE]"
CONSTANT cs_note_tag        STRING = "[NOTE]"
CONSTANT cs_success_tag     STRING = "[SUCCESS]"

CONSTANT cs_null_default STRING = "@#$%"

CONSTANT cs_modify_type_insert STRING = "I"
CONSTANT cs_modify_type_update STRING = "U"

CONSTANT cs_open_paren  STRING = "("
CONSTANT cs_close_paren STRING = ")"

CONSTANT cs_CRLF  STRING = "\n"
CONSTANT cs_SPACE STRING = " "

CONSTANT cs_divide STRING = "|"

CONSTANT cs_response_yes STRING = "yes"    
CONSTANT cs_response_no  STRING = "no" 

CONSTANT cs_default_language STRING = "zh_TW"

CONSTANT cs_topstd_user_name STRING = "topstd"

CONSTANT cs_state_enable  STRING = "Enable"
CONSTANT cs_state_disable STRING = "Disable"
