CONSTANT cs_user_role_all      STRING = "ALL"
CONSTANT cs_user_role_pr       STRING = "PR"
CONSTANT cs_user_role_sd       STRING = "SD"
CONSTANT cs_user_role_registry STRING = "RG"

CONSTANT cs_check_out VARCHAR = "O"
CONSTANT cs_check_in  VARCHAR = "I"

CONSTANT cs_dgenv_standard  VARCHAR = "s"
CONSTANT cs_dgenv_customize VARCHAR = "c"  

CONSTANT cs_interface_type_prev STRING = "PREV"
CONSTANT cs_interface_type_curr STRING = "CURR"

CONSTANT cs_spec_type_table  STRING = "T"

CONSTANT cs_alm_main_table STRING = "DZLM_T"

CONSTANT cs_disable_alm_request_no  STRING = "000000-00000"
CONSTANT cs_disable_alm_sequence_no STRING = "0"

CONSTANT cs_topstd_request_no  STRING = "999999-99999"
CONSTANT cs_topstd_sequence_no STRING = "9"

CONSTANT cs_industry_type_standard STRING = "sd"

CONSTANT ci_unlimit_number    INTEGER = -1
CONSTANT ci_min_number        INTEGER = 0
CONSTANT ci_construct_ver_one INTEGER = 1

CONSTANT cs_max_increase_number STRING = "MaxIncreaseNumber"
CONSTANT cs_min_decrease_number STRING = "MinDecreaseNumber"

CONSTANT cs_ver_type_construct STRING = "Construct"
CONSTANT cs_ver_type_sd        STRING = "SD"
CONSTANT cs_ver_type_pr        STRING = "PR"

CONSTANT cs_release_yes   STRING = "Y"
CONSTANT cs_release_no    STRING = "N"
CONSTANT cs_release_mark  STRING = "M"

CONSTANT cs_prog_type_4gl STRING = "4gl"
CONSTANT cs_prog_type_4fd STRING = "4fd"
