      <tr style='mso-yfti-irow:3;height:30.8pt'>
      <td width=50 style='width:37.3pt;border-top:none;border-left:solid black 1.0pt;
      border-bottom:solid black 1.0pt;border-right:none;background:white;
      padding:0cm 5.4pt 0cm 5.4pt;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      lang=EN-US style='font-family:"微軟正黑體","sans-serif"'>{$D1}<o:p></o:p></span></p>
      </td>
      <td width=143 style='width:102.4pt;border:none;border-bottom:solid black 1.0pt;
      background:white;padding:0cm 5.4pt 0cm 5.4pt;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D2}</span></p>
      </td>
      <td width=137 style='width:102.4pt;border:none;border-bottom:solid black 1.0pt;
      background:white;padding:0cm 5.4pt 0cm 5.4pt;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D21}</span></p>
      </td>      
      <td width=48 style='width:36.2pt;border:none;border-bottom:solid black 1.0pt;
      background:white;padding:0cm 5.4pt 0cm 5.4pt;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D22}</span></p>
      </td>
      <td width=129 colspan=2 style='width:96.7pt;border:none;border-bottom:
      solid black 1.0pt;background:white;padding:0cm 5.4pt 0cm 5.4pt;
      height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      lang=EN-US style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D3}<o:p></o:p></span></p>
      </td>
      <td width=114 colspan=3 style='width:85.25pt;border:none;border-bottom:
      solid black 1.0pt;background:white;padding:0cm 5.4pt 0cm 5.4pt;
      height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      lang=EN-US style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D4}<o:p></o:p></span></p>
      </td>
      <td width=107 colspan=2 style='width:79.9pt;border:none;border-bottom:
      solid black 1.0pt;background:white;padding:0cm 0cm 0cm 0cm;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      lang=EN-US style='font-family:"微軟正黑體","sans-serif";color:#0070C0'>{$D5}<o:p></o:p></span></p>
      </td>
      <td width=100 colspan=2 style='width:75.2pt;border-top:none;border-left:
      none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;
      background:white;padding:0cm 5.4pt 0cm 5.4pt;height:30.8pt'>
      <p class=MsoNormal align=center style='text-align:center'><span
      lang=EN-US style='font-family:"微軟正黑體","sans-serif"'>{$D6}<o:p></o:p></span></p>
      </td>
     </tr>
