SCHEMA ds

GLOBALS
  #DEFINE g_apmp610_03_input     RECORD
  #                                 sscb01    LIKE type_t.chr10
  #                              END RECORD   
   DEFINE g_d_cnt_p61004_01      LIKE type_t.num5
   DEFINE g_appoint_idx          LIKE type_t.num5
   DEFINE g_d_idx_p61004_01      LIKE type_t.num5
   DEFINE g_d_cnt_p61004_02      LIKE type_t.num5
   DEFINE g_d_idx_p61004_02      LIKE type_t.num5
   DEFINE g_d_cnt_p61004_03      LIKE type_t.num5
   DEFINE g_d_idx_p61004_03      LIKE type_t.num5   
   DEFINE g_d_cnt_p61004_04      LIKE type_t.num5   
   DEFINE g_d_idx_p61004_04      LIKE type_t.num5
END GLOBALS
